name: "${project.name}"
description: ${project.description}
version: ${project.version}
main: org.avarion.pluginhider.PluginHider
api-version: "1.16"
author: svaningelgem
load: STARTUP
website: https://github.com/AvarionMC/PluginHider

depend:
  - packetevents

commands:
  pluginhider:
    description: Reloads the PluginHiders configuration
    usage: /pluginhider reload
    aliases: [ ph ]
